# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-04 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_type',
            field=models.IntegerField(choices=[(1, 'tarea'), (2, 'evaluacion'), (3, 'conducta'), (4, 'examen'), (5, 'cuaderno'), (6, 'simulacro')], default=1, verbose_name='Tipo de nota'),
        ),
    ]
