# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-05-04 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_auto_20190504_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
