version: '2'  
services:  
  nginx:
    image: nginx:latest
    container_name: nginx-fractal-django
    ports:
      - "8000:8000"
    volumes:
      - ./fractal-django:/fractal-django
      - ./config/nginx:/etc/nginx/conf.d
      - /static:/static 
    depends_on:
      - fractal.edu.pe
  fractal.edu.pe:
    build: .
    container_name: fractal-django
    command: bash -c "python manage.py makemigrations && python manage.py collectstatic --noinput && python manage.py migrate && gunicorn fractal.wsgi -b 0.0.0.0:8000 --reload"
    volumes:
      - ./fractal-django:/fractal-django
      - /static:/static  
    expose:
      - "8000"
    depends_on:
      - db
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  #certbot:
  #  image: certbot/certbot
  #  container-name: fractal-certbot
  #  volumes:
  #    - ./data/certbot/conf:/etc/letsencrypt
  #    - ./data/certbot/www:/var/www/certbot

volumes:
  postgres_data:
