# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-01 00:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencia', '0003_grade_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de pago')),
                ('receipt_nro', models.IntegerField(verbose_name='Numero de recibo')),
                ('pay_reference', models.IntegerField(choices=[('1', 'Matricula'), ('2', 'Marzo'), ('3', 'Abril'), ('4', 'Mayo'), ('5', 'Junio'), ('6', 'Julio'), ('7', 'Agosto'), ('8', 'Septiembre'), ('9', 'Octubre'), ('10', 'Noviembre'), ('11', 'Diciembre')], verbose_name='Concepto')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Monto')),
            ],
            options={
                'verbose_name_plural': 'Pagos',
                'verbose_name': 'Pago',
            },
        ),
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Matricula')),
                ('monthly_amount', models.DecimalField(decimal_places=2, default=300.0, max_digits=6, verbose_name='Mensualidad')),
                ('has_promo', models.BooleanField(default=False, verbose_name='Tiene promocion?')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.Matricula')),
            ],
            options={
                'verbose_name_plural': 'Configuraciones de pagos',
                'verbose_name': 'Configuracion de pagos',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.PaymentSettings'),
        ),
    ]
