# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-03-02 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20190601_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsettings',
            name='first_month',
            field=models.IntegerField(choices=[(1, 'Marzo'), (2, 'Abril'), (3, 'Mayo'), (4, 'Junio'), (5, 'Julio'), (6, 'Agosto'), (7, 'Septiembre'), (8, 'Octubre'), (9, 'Noviembre'), (10, 'Diciembre')], default=1, verbose_name='Primer mes de pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_reference',
            field=models.IntegerField(choices=[(0, 'Matricula'), (1, 'Marzo'), (2, 'Abril'), (3, 'Mayo'), (4, 'Junio'), (5, 'Julio'), (6, 'Agosto'), (7, 'Septiembre'), (8, 'Octubre'), (9, 'Noviembre'), (10, 'Diciembre')], verbose_name='Concepto'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='matricula_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Monto de la Matricula'),
        ),
        migrations.AlterField(
            model_name='paymentsettings',
            name='monthly_amount',
            field=models.DecimalField(decimal_places=2, default=300.0, max_digits=6, verbose_name='Monto de la Mensualidad'),
        ),
    ]
